Create vivliostyle report 2022 en
vivliostyle/vivliostyle_doc pull request #19
Opened 2023-07-18 08:23 UTC by ogwata

英訳版です。ご確認ください。

2023-07-18 10:01 UTC, MurakamiShinyu commented
英語・日本語ともですが、図2のあとの文章で、「ピンク色の線(pink line)」、「赤色の線(red line)」と書かれていますが、図2でのそれらの実際の線の色はそれぞれ（ピンクというより）赤、（赤というより）茶色に見えます。

2023-07-18 10:33 UTC, MurakamiShinyu commented on en/reports/vivliostyle-report-2022/vf2022report.md
> +> Catches the eye is that “Business income” raised 6,267,250 yen, which is 4,763,529 yen more than the previous fi scal year. (omitted) Thiswas due to the expansion of contract development from exter
この単語内に余計なスペースが入っていたり("fi scal")、単語間のスペースがなくなったり("Thiswas")してます。Adobe AcrobatでPDFからコピーするとこの問題がおきます。コピペはなるべくHTMLやMDからのほうがよいです。

それから、"Catches" ではじまってますが、もとの文は "what catches the eye" が主語なので "What" も入れないとおかしいです。

```suggestion
> What catches the eye is that “Business income” raised 6,267,250 yen, which is 4,763,529 yen more than the previous fiscal year. (omitted) This was due to the expansion of contract development from external companies.
```

2023-07-18 10:35 UTC, MurakamiShinyu commented on en/reports/vivliostyle-report-2022/vf2022report.md
> +### Income and Expenditure Statement for FY2021
```suggestion
### Income and Expenditure Statement for FY2022
```

2023-07-18 12:30 UTC, ogwata commented
> 英語・日本語ともですが、図2のあとの文章で、「ピンク色の線(pink line)」、「赤色の線(red line)」と書かれていますが、図2でのそれらの実際の線の色はそれぞれ（ピンクというより）赤、（赤というより）茶色に見えます。

修正しました。なお、jaの図2も修正する必要がありますが、マージ後にgh-pagesへのコミットとして同じ修正をします（他にも修正が必要なケアレスミスがあるので）。

2023-07-18 12:37 UTC, MurakamiShinyu commented
fig-2.svg の修正、不完全です。線の色の説明してるところの色が修正されていません。

![スクリーンショット 2023-07-18 21 35 25](https://github.com/vivliostyle/vivliostyle_doc/assets/3324737/415d36ae-6aad-4f55-82ae-07d30e726533)

2023-07-18 12:39 UTC, ogwata commented
> fig-2.svg の修正、不完全です。線の色の説明してるところの色が修正されていません。
> 
> ![スクリーンショット 2023-07-18 21 35 25](https://user-images.githubusercontent.com/3324737/254264236-415d36ae-6aad-4f55-82ae-07d30e726533.png)


`50d9fee`のコミットで修正しています。ご確認ください。

2023-07-18 13:08 UTC, ogwata commented
188行と239行の間違いを`721b06a`で修正しました。

2023-07-18 14:05 UTC, MurakamiShinyu requested changes

2023-07-18 14:05 UTC, MurakamiShinyu commented on en/reports/vivliostyle-report-2022/vf2022report.md
> +### Analysis of PR Creator
複数形に

```suggestion
### Analysis of PR Creators
```

2023-07-18 14:05 UTC, MurakamiShinyu commented on en/reports/vivliostyle-report-2022/vf2022report.md
> +As can be seen from these tables, in the groups that developed smoothly, it was Representative Murakami who created many of the PRs. On the other hand, in the group that did not perform so well, the
"the Murakami representatives were" がおかしい

```suggestion
As can be seen from these tables, in the groups that developed smoothly, it was Representative Murakami who created many of the PRs. On the other hand, in the group that did not perform so well, Murakami was less involved.
```

2023-07-18 14:05 UTC, MurakamiShinyu commented on en/reports/vivliostyle-report-2022/vf2022report.md
> +Incidentally, looking at the PR content of Representative Murakami for Vivliostyle CLI and Vivliostyle Pub, it is clear that it is not PR to add original functions to Vivliostyle CLI or Vivliostyle P
英文がおかしい

```suggestion
Incidentally, looking at the PR content of Representative Murakami for Vivliostyle CLI and Vivliostyle Pub, it is clear that it is not PR to add original functions to Vivliostyle CLI or Vivliostyle Pub, but rather to spread the feature additions and bug fixes in Vivliostyle.js, for which he himself is the maintainer, to each of them.
```

2023-07-18 14:05 UTC, MurakamiShinyu commented on en/reports/vivliostyle-report-2022/vf2022report.md
> +The [PR](https://github.com/vivliostyle/vivliostyle.js/pull/1090) by Mr. [hkwi](https://github.com/hkwi), shown above, adds the CSS leader (), which provides the ruled line functionality often used i
"leader()" の括弧は関数形式を表すものなのでスペースを入れない。
"and other documents"（その他の文書に）は余計。

```suggestion
The [PR](https://github.com/vivliostyle/vivliostyle.js/pull/1090) by Mr. [hkwi](https://github.com/hkwi), shown above, adds the CSS leader(), which provides the ruled line functionality often used in table of contents. This has been an issue for some time and is a long-awaited addition.
```

2023-07-18 15:06 UTC, MurakamiShinyu commented on en/reports/vivliostyle-report-2022/report.css
> +
生成されたPDFを見て、p.9〜p.10でTable-1が分割されているのが気になりました。このTableはfigure要素で囲んでます。ほかのfigure要素も1ページ内に収めるべきものです。そこでfigureにbreak-inside:avoidを指定して分割されないようにするのがよさそうです。

```suggestion

figure {
  break-inside: avoid;
}

```

2023-07-19 10:06 UTC, MurakamiShinyu commented on en/reports/vivliostyle-report-2021/report.css
2021年度のreport.cssが変更されていますが、これは必要な変更ですか？

2023-07-19 11:43 UTC, ogwata commented on en/reports/vivliostyle-report-2021/report.css
いえ、`en/reports/vivliostyle-report-2021/report.css`は変更したつもりはありません。

2023-07-19 13:12 UTC, MurakamiShinyu approved these changes

2023-07-19 13:35 UTC, merged